WhareHauora/wharehauora-server

.travis.yml
app/controllers/application_controller.rb
app/controllers/homes_controller.rb
app/controllers/sensors_controller.rb
app/models/role.rb
app/models/user.rb
app/models/user_role.rb
app/policies/application_policy.rb
app/policies/home_policy.rb
app/policies/sensor_policy.rb
db/migrate/20161203031122_create_roles.rb
db/schema.rb
db/seeds.rb
spec/controllers/homes_controller_spec.rb
spec/controllers/sensors_controller_spec.rb
spec/factories/roles.rb
spec/models/user_spec.rb

Adding user roles

---

.travis.yml

Add brakeman to travis

---

Gemfile
Gemfile.lock
app/controllers/welcome_controller.rb
app/views/welcome/index.haml
db/migrate/20161217062517_create_median_function.rb
db/schema.rb

Show median values on front page

---

app/views/welcome/index.haml

Reverts WhareHauora/wharehauora-server#98

Revert "Removed signin from front page"

---

app/assets/stylesheets/layout.css.scss
app/helpers/welcome_helper.rb
app/views/layouts/application.haml
app/views/rooms/index.haml
app/views/welcome/index.haml

New front page with temps and colours

---

app/controllers/rooms_controller.rb
app/models/room.rb
app/models/sensor.rb
app/policies/room_policy.rb
app/views/homes/_nav.haml
app/views/rooms/edit.haml
app/views/rooms/index.haml
app/views/rooms/show.haml
app/views/sensors/_card.haml
app/views/sensors/_form.haml
app/views/sensors/edit.haml
app/views/sensors/index.haml

More room display clean up, and showing unassigned sensors

---

Gemfile
Gemfile.lock
app/controllers/admin/users_controller.rb
app/models/user.rb
app/views/admin/users/_table.haml
app/views/admin/users/edit.haml
db/migrate/20170725084656_add_deleted_at_to_users.rb
db/structure.sql
spec/features/admin/users_spec.rb

The user's data doesn't do away, but they can no longer log in

soft delete of users

---

Gemfile
Gemfile.lock

as suggested by @mihado on #280

Swap acts_as_paranoid gem for paranoia gem

---

app/models/sensor.rb
db/migrate/20170804072223_room_sensors_count.rb
db/structure.sql

Small performance gain - the number of sensors is saved against the room, saving a query.

Added room.sensors counter cache

---

app/views/welcome/index.haml

Quickly add Rabid and OshPark to front page

---

app/policies/room_policy.rb
app/policies/sensor_policy.rb
app/views/rooms/_card.haml
spec/features/welcome_spec.rb

Fixes error when not-logged-in user tries to view a room from the front page

---

app/views/welcome/index.haml

And clarify that our sensors are free (as people are concluding we are selling them)

Fix grammar

---

app/policies/reading_policy.rb

Readings api is throwing errors - this fixes it.
https://github.com/WhareHauora/App/issues/68

Fix the readings permissions

---

app/resources/api/v1/home_resource.rb
app/resources/api/v1/room_resource.rb
app/resources/api/v1/sensor_resource.rb
app/resources/api/v1/user_resource.rb
config/routes.rb

More filters to use on the API

Adding filters

---

config/routes.rb
db/migrate/20160922042938_devise_create_users.rb
db/migrate/20170416021403_counter_caches.rb

Auto corrected by following EmptyLine
Click [here](https://awesomecode.io/projects/57/ruby_config_groups/534) to configure it on awesomecode.io

Auto corrected by following EmptyLine

---

spec/controllers/homes_controller_spec.rb
spec/controllers/rooms_controller_spec.rb
spec/models/reading_spec.rb

Auto corrected by following Ruby FactoryBot/CreateList
Click [here](https://awesomecode.io/projects/57/ruby_configs/26193) to configure it on awesomecode.io

Auto corrected by following Ruby FactoryBot/CreateList

---

bin/setup
db/migrate/20170519023216_create_doorkeeper_tables.rb
db/migrate/20170801095409_add_confirmed_at_to_users.rb

Auto corrected by following Ruby Layout/ExtraSpacing
Click [here](https://awesomecode.io/projects/57/ruby_configs/14476) to configure it on awesomecode.io

Auto corrected by following Ruby Layout/ExtraSpacing

---

bin/bundle
bin/setup
bin/update

Auto corrected by following Ruby Style/ExpandPathArguments
Click [here](https://awesomecode.io/projects/57/ruby_configs/18427) to configure it on awesomecode.io

Auto corrected by following Ruby Style/ExpandPathArguments

---

spec/controllers/readings_controller_spec.rb
spec/features/menu/menu_spec.rb
spec/helpers/readings_helper_spec.rb
spec/helpers/sensors_helper_spec.rb
spec/services/room_service_spec.rb

Auto corrected by following Ruby rspec layout
Click [here](https://awesomecode.io/projects/57/ruby_config_groups/740) to configure it on awesomecode.io

Auto corrected by following Ruby rspec layout

---

app/helpers/sensors_helper.rb
app/models/room.rb

Auto corrected by following Ruby EmptyLine
Click [here](https://awesomecode.io/projects/57/ruby_config_groups/534) to configure it on awesomecode.io

Auto corrected by following Ruby EmptyLine

---

app/views/layouts/_menu.haml

Provide a general summary of your changes in the Title above
- Please include a summary of the change and which issue is fixed.
- Please also include relevant motivation and context.
- List any dependencies that are required for this change.
Delete any lines that don't apply
* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to change)
* Documentation change
Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!

Fixed link on logo

---

app/controllers/user/registrations_controller.rb
app/views/devise/sessions/new.html.haml
app/views/layouts/_flash.html.haml
app/views/layouts/_scripts.html.haml
app/views/layouts/devise.haml
spec/features/menu/menu_spec.rb

Tidy up layout for log in and registation pages

---

app/controllers/user/registrations_controller.rb

Auto corrected by following Ruby MagicComment
Click [here](https://awesomecode.io/projects/57/ruby_config_groups/537) to configure it on awesomecode.io

Auto corrected by following Ruby MagicComment

---

app/views/admin/home_types/edit.haml
app/views/admin/home_types/index.haml
app/views/admin/home_types/new.haml
app/views/admin/mqtt_users/index.haml
app/views/admin/room_types/edit.haml
app/views/admin/room_types/index.haml
app/views/admin/room_types/new.haml
app/views/admin/users/edit.haml
app/views/admin/users/index.haml
app/views/devise/passwords/edit.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/registrations/edit.html.haml
app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/devise/unlocks/new.html.haml
app/views/home_viewers/index.haml
app/views/home_viewers/new.haml
app/views/homes/edit.haml
app/views/homes/index.haml
app/views/homes/new.haml
app/views/messages/index.haml
app/views/readings/index.haml
app/views/rooms/edit.haml
app/views/rooms/index.haml
app/views/sensors/edit.haml
app/views/sensors/show.haml

added `content_for :title` to all pages

Adding titles to all pages
